SpendManagingReview/Models/SpendReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SpendManagingReview.Models
{
    public class SpendReport
    {
        [Key]
        public int ItemId { get; set; }
        [Required]
        public string ItemName { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Amount { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime SpendDate { get; set; } = DateTime.Now;

        [Required]
        public string Category { get; set; }
    }
}

SpendManagingReview/Controllers/SpendController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using SpendManagingReview.Models;

namespace SpendManagingReview.Controllers
{
    public class SpendController : Controller
    {
        SpendDAL objSpend = new SpendDAL();
        public IActionResult Index(string searchString)
        {
            List<SpendReport> lstEmployee = new List<SpendReport>();
            lstEmployee = objSpend.GetAllSpend().ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                lstEmployee = objSpend.GetSearchResult(searchString).ToList();
            }
            return View(lstEmployee);
        }

        public ActionResult AddEditSpend(int itemId)
        {
            SpendReport model = new SpendReport();
            if (itemId > 0)
            {
                model = objSpend.GetSpendData(itemId);
            }
            return PartialView("_spendForm", model);
        }

        [HttpPost]
        public ActionResult Create(SpendReport newSpend)
        {
            if (ModelState.IsValid)
            {
                if (newSpend.ItemId > 0)
                {
                    objSpend.UpdateSpend(newSpend);
                }
                else
                {
                    objSpend.AddSpend(newSpend);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            objSpend.DeleteSpend(id);
            return RedirectToAction("Index");
        }

        public ActionResult SpendSummary()
        {
            return PartialView("_spendReport");
        }

        public JsonResult GetMonthlySpend()
        {
            Dictionary<string, decimal> monthlySpend = objSpend.CalculateMonthlySpend();
            return new JsonResult(monthlySpend);
        }

        public JsonResult GetWeeklySpend()
        {
            Dictionary<string, decimal> weeklySpend = objSpend.CalculateWeeklySpend();
            return new JsonResult(weeklySpend);
        }
    }
}

SpendManagingReview/Views/Spend/Index.cshtml
@model IEnumerable<SpendManagingReview.Models.SpendReport>

@{
    ViewData["Title"] = "Personal Spend Manager";
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" rel="stylesheet">

<h2>Personal Spend Manager</h2>
<br />
<div>
    <div style="float:left">
        <button class="btn btn-primary" onclick="AddEditSpend(0)">Add Spend</button>
        <button class="btn btn-success" onclick="ReportSpend()">Spend Report</button>
    </div>
    <div style="float:right; width:40%;">
        <form asp-controller="Spend" asp-action="Index" class="form-group">
            <div class="col-sm-6">
                <input class="form-control" type="text" name="SearchString" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default btn-info">Find</button>
        </form>
    </div>
</div>
<br />
<br />
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ItemId)</th>
            <th>@Html.DisplayNameFor(model => model.ItemName)</th>
            <th>@Html.DisplayNameFor(model => model.Amount)</th>
            <th>@Html.DisplayNameFor(model => model.SpendDate)</th>
            <th>@Html.DisplayNameFor(model => model.Category)</th>
            <th>Action Item</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.ItemId)</td>
                <td>@Html.DisplayFor(modelItem => item.ItemName)</td>
                <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                <td>@Html.DisplayFor(modelItem => item.SpendDate)</td>
                <td>@Html.DisplayFor(modelItem => item.Category)</td>
                <td>
                    <button class="btn btn-default" onclick="AddEditSpend(@item.ItemId)">Edit</button>
                    <button class="btn btn-danger" onclick="DeleteSpend(@item.ItemId)">Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="spendFormModel" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 id="title" class="modal-title">Add</h3>
            </div>
            <div class="modal-body" id="spendFormModelDiv">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="spendReportModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title">Spend Report</h3>
            </div>
            <div class="modal-body" id="spendReportModalDiv">
            </div>
        </div>
    </div>
</div>

<script>

    var AddEditSpend = function (itemId) {
        var url = "/Spend/AddEditSpend?itemId=" + itemId;
        if (itemId > 0)
            $('#title').html("Edit Spend");

        $("#spendFormModelDiv").load(url, function () {
            $("#spendFormModel").modal("show");

        });

        $('#spendFormModel').on('shown.bs.modal', function () {

            $('#calender-container .input-group.date').datepicker({
                todayBtn: true,
                calendarWeeks: true,
                todayHighlight: true,
                autoclose: true,
                container: '#spendFormModel modal-body'
            });

        });
    }

    var ReportSpend = function () {
        var url = "/Spend/SpendSummary";

        $("#spendReportModalDiv").load(url, function () {
            $("#spendReportModal").modal("show");
        })
    }

    var DeleteSpend = function (itemId) {

        var ans = confirm("Do you want to delete item with Item Id: " + itemId);

        if (ans) {
            $.ajax({
                type: "POST",
                url: "/Spend/Delete/" + itemId,
                success: function () {
                    window.location.href = "/Spend/Index";
                }
            })
        }
    }
</script>

<script>

    $('body').on('click', "#btnSubmit", function () {
        var myformdata = $("#spendForm").serialize();

        $.ajax({
            type: "POST",
            url: "/Spend/Create",
            data: myformdata,
            success: function () {
                $("#myModal").modal("hide");
                window.location.href = "/Spend/Index";
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        })
    })
</script>

SpendManagingReview/Views/Spend/_spendForm.cshtml
@model SpendManagingReview.Models.SpendReport

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" rel="stylesheet">

<div>
    <div class="row">
        <div class="col-md-8">
            <form id="spendForm">
                <input type="hidden" asp-for="ItemId" />
                <div class="form-group">
                    <label asp-for="ItemName" class="control-label"></label>
                    <input asp-for="ItemName" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <select asp-for="Category" class="form-control">
                        <option value="">-- Select Category --</option>
                        <option value="Food">Food</option>
                        <option value="Shopping">Shopping</option>
                        <option value="Travel">Travel</option>
                        <option value="Health">Health</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="Amount" class="control-label"></label>
                    <input asp-for="Amount" class="form-control" />
                </div>
                <div class="form-group" id="calender-container">
                    <label asp-for="SpendDate" class="control-label"></label>
                    <div class="input-group date">
                        <input asp-for="SpendDate" type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                </div>
                <div class="form-group">
                    <button type="button" id="btnSubmit" class="btn btn-block btn-info">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

SpendManagingReview/Views/Spend/_spendReport.cshtml
<script src="https://code.highcharts.com/highcharts.js"></script>

<button id="btnMonthlyReport" class="btn btn-info">Monthly Report</button>
<button id="btnWeeklyReport" class="btn btn-warning">Weekly Report</button>
<div id="container" style="min-width: 400px; height: 400px; margin: 0 auto">

</div>

<script>

    $(document).ready(function () {
        $("#btnWeeklyReport").click(function () {
            var titleMessage = "Costs in last four weeks is : ";

            $.ajax({
                type: "GET",
                url: "/Spend/GetWeeklySpend",
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    var keys = Object.keys(result);
                    var weeklydata = new Array();
                    var totalspent = 0.0;
                    for (var i = 0; i < keys.length; i++) {
                        var arrL = new Array();
                        arrL.push(keys[i]);
                        arrL.push(result[keys[i]]);
                        totalspent += result[keys[i]];
                        weeklydata.push(arrL);
                    }
                    createCharts(weeklydata, titleMessage, totalspent.toFixed(2));
                }
            })
        })

        $("#btnMonthlyReport").click(function () {
            var titleMessage = "Costs in last six months is : ";

            $.ajax({
                type: "GET",
                url: "/Spend/GetMonthlySpend",
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    var keys = Object.keys(result);
                    var monthlydata = new Array();
                    var totalspent = 0.0;
                    for (var i = 0; i < keys.length; i++) {
                        var arrL = new Array();
                        arrL.push(keys[i]);
                        arrL.push(result[keys[i]]);
                        totalspent += result[keys[i]];
                        monthlydata.push(arrL);
                    }
                    createCharts(monthlydata, titleMessage, totalspent.toFixed(2));
                }
            })
        })
    })

    function createCharts(sum, titleText, totalspent) {
        Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: titleText + ' ' + totalspent
            },
            xAxis: {
                type: 'category',
                labels: {
                    rotation: -45,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif'
                    }
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Money spent'
                }
            },
            legend: {
                enabled: false
            },
            tooltip: {
                pointFormat: 'Total money spent: <b>{point.y:.2f} </b>'
            },
            series: [{
                type: 'column',
                data: sum,
            }]
        });
    }

</script>